import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'yukito' at '16/05/31 22:09' with Gradle 2.9
 *
 * @author yukito, @date 16/05/31 22:09
 */
public class LibraryTest {
	@Test
	public void testSomeLibraryMethod() {
	}
}
